### ISSUE TITLE
Method error

### ISSUE THREAD

**Issue by TeAmP0is0N** [SciML/NeuralNetDiffEq.jl#88] opened 2020-05-28 15:40 UTC
https://github.com/SciML/NeuralNetDiffEq.jl/blob/80045e0c6332e1d3a160b7b42d7390c457abaa31/test/NNODE_tests.jl#L16
```
opt = BFGS()
sol = solve(prob, NeuralNetDiffEq.NNODE(chain,opt), dt=1/20f0, verbose = true,
            abstol=1e-10, maxiters = 200)
```

```
MethodError: no method matching apply!(::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}, ::Array{Float32,2}, ::Array{Float64,2})
Closest candidates are:
  apply!(!Matched::Descent, ::Any, ::Any) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\optimisers.jl:40
  apply!(!Matched::Momentum, ::Any, ::Any) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\optimisers.jl:70
  apply!(!Matched::Nesterov, ::Any, ::Any) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\optimisers.jl:103
  ...

Stacktrace:
 [1] update!(::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}, ::Array{Float32,2}, ::Array{Float64,2}) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:25
 [2] update!(::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}, ::Zygote.Params, ::Zygote.Grads) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:31
 [3] macro expansion at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:92 [inlined]
 [4] macro expansion at C:\Users\TeAmp0is0N\.julia\packages\Juno\tLMZd\src\progress.jl:134 [inlined]
 [5] train!(::NeuralNetDiffEq.var"#4#13"{ODEFunction{false,var"#3#4",LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},DiffEqBase.NullParameters,StepRangeLen{Float32,Float64,Float64},NeuralNetDiffEq.var"#phi#11"{Float32,Tuple{Float32,Float32},Chain{Tuple{Dense{typeof(σ),Array{Float32,2},Array{Float32,1}},Dense{typeof(identity),Array{Float32,2},Array{Float32,1}}}}}}, ::Zygote.Params, ::Base.Iterators.Take{Base.Iterators.Repeated{Tuple{}}}, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}; cb::NeuralNetDiffEq.var"#9#18"{Float64,Bool}) at C:\Users\TeAmp0is0N\.julia\packages\Flux\Fj3bt\src\optimise\train.jl:81
 [6] solve(::ODEProblem{Float32,Tuple{Float32,Float32},false,DiffEqBase.NullParameters,ODEFunction{false,var"#3#4",LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},DiffEqBase.StandardODEProblem}, ::NNODE{Chain{Tuple{Dense{typeof(σ),Array{Float32,2},Array{Float32,1}},Dense{typeof(identity),Array{Float32,2},Array{Float32,1}}}},BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}}; dt::Float32, timeseries_errors::Bool, save_everystep::Bool, adaptive::Bool, abstol::Float64, verbose::Bool, maxiters::Int64) at C:\Users\TeAmp0is0N\.julia\packages\NeuralNetDiffEq\BNep9\src\ode_solve.jl:55
 [7] top-level scope at In[6]:2
```

**Comment by TeAmP0is0N** [comment] 2020-05-28 15:44
@ChrisRackauckas Please have a look. I am not getting this correctly.

**Comment by ChrisRackauckas** [comment] 2020-05-28 16:54
`]st`?

**Comment by TeAmP0is0N** [comment] 2020-05-28 17:05
> `]st`?

``` [3895d2a7] CUDAapi v4.0.0
  [c5f51814] CUDAdrv v6.3.0
  [be33ccc6] CUDAnative v3.1.0
  [e2554f3b] Clp v0.8.0
  [3a865a2d] CuArrays v2.2.0
  [2b5f629d] DiffEqBase v6.35.2
  [f3b72e0c] DiffEqDevTools v2.21.0
  [41bf760c] DiffEqSensitivity v6.17.0
  [0c46a032] DifferentialEquations v6.14.0
  [587475ba] Flux v0.10.4
  [c91e804a] Gadfly v1.2.1
  [7073ff75] IJulia v1.21.2
  [4076af6c] JuMP v0.21.2
  [1902f260] Knet v1.3.5
  [8faf48c0] NeuralNetDiffEq v1.4.0
  [429524aa] Optim v0.20.1
  [91a5bcdd] Plots v1.3.5
  [438e738f] PyCall v1.91.4
  [189a3867] Reexport v0.2.0
  [9f7883ad] Tracker v0.2.6
  [e88e6eb3] Zygote v0.4.20
```

**Comment by ChrisRackauckas** [comment] 2020-05-28 18:43
I think this is a versioning issue. I put a patch in. v1.5 of NeuralNetDiffEq should get released in about 1 hour and you should update and we should see if that fixes it. Your Optim should be v0.21: I think that's the cause of all of your problems. Why your Optim is such an older version is a big question, but hopefully it's just some Compat thing that was caused by NeuralNetDiffEq missing a tag.

https://github.com/JuliaNLSolvers/Optim.jl/releases

**Comment by TeAmP0is0N** [comment] 2020-05-28 19:49
Yeah, I updated `Optim` but I am getting `Optim v0.20.1` not `Optim v0.21.1` .

**Comment by ChrisRackauckas** [comment] 2020-05-28 19:49
can you try `]add Optim@0.21.0` and see what it throws?

**Comment by TeAmP0is0N** [comment] 2020-05-28 19:51
```add Optim@0.21.0
  Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Gadfly [c91e804a]:
 Gadfly [c91e804a] log:
 ├─possible versions are: [0.8.0, 1.0.0-1.0.1, 1.1.0, 1.2.0-1.2.1] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.8.0, 1.0.0-1.0.1, 1.1.0, 1.2.0-1.2.1]
 ├─restricted by compatibility requirements with Compat [34da2185] to versions: 1.2.0-1.2.1 or uninstalled, leaving only versions: 1.2.0-1.2.1
 │ └─Compat [34da2185] log:
 │   ├─possible versions are: [1.0.0-1.0.1, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.5.0-1.5.1, 2.0.0, 2.1.0, 2.2.0, 3.0.0, 3.1.0, 3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0] or uninstalled
 │   └─restricted by compatibility requirements with Optim [429524aa] to versions: [3.2.0, 3.3.0-3.3.1, 3.4.0, 3.5.0, 3.6.0, 3.7.0, 3.8.0, 3.9.0-3.9.1, 3.10.0]
 │     └─Optim [429524aa] log:
 │       ├─possible versions are: [0.15.3, 0.16.0, 0.17.0-0.17.2, 0.18.0-0.18.1, 0.19.0-0.19.7, 0.20.0-0.20.6, 0.21.0] or uninstalled
 │       └─restricted to versions 0.21.0 by an explicit requirement, leaving only versions 0.21.0
 └─restricted by compatibility requirements with CoupledFields [7ad07ef1] to versions: [0.8.0, 1.0.0-1.0.1] or uninstalled — no versions left
   └─CoupledFields [7ad07ef1] log:
     ├─possible versions are: [0.1.0, 0.2.0] or uninstalled
     ├─restricted by compatibility requirements with Gadfly [c91e804a] to versions: [0.1.0, 0.2.0]
     │ └─Gadfly [c91e804a] log: see above
     └─restricted by compatibility requirements with Compat [34da2185] to versions: 0.2.0 or uninstalled, leaving only versions: 0.2.0
       └─Compat [34da2185] log: see above
```

**Comment by ChrisRackauckas** [comment] 2020-05-28 19:52
Remove Gadfly.

**Comment by TeAmP0is0N** [comment] 2020-05-28 20:02
Yeah, removed and got optim 0.21.0

**Comment by ChrisRackauckas** [comment] 2020-05-28 20:02
Then restarting Julia fixed it?

**Comment by TeAmP0is0N** [comment] 2020-05-28 20:07
No, it throws this.
```
using NeuralNetDiffEq
[ Info: Precompiling NeuralNetDiffEq [8faf48c0-8b73-11e9-0e63-2155955bfa4d]
Cannot write cache file "C:\Users\TeAmp0is0N\.julia\compiled\v1.4\NeuralNetDiffEq\OEfxR_vvRhQ.ji".
ERROR: Failed to precompile NeuralNetDiffEq [8faf48c0-8b73-11e9-0e63-2155955bfa4d] to C:\Users\TeAmp0is0N\.julia\compiled\v1.4\NeuralNetDiffEq\OEfxR_vvRhQ.ji.
Stacktrace:
 [1] error(::String) at .\error.jl:33
 [2] compilecache(::Base.PkgId, ::String) at .\loading.jl:1272
 [3] _require(::Base.PkgId) at .\loading.jl:1029
 [4] require(::Base.PkgId) at .\loading.jl:927
 [5] require(::Module, ::Symbol) at .\loading.jl:922
```

**Comment by ChrisRackauckas** [comment] 2020-05-28 20:10
Permissions issues?

**Comment by TeAmP0is0N** [comment] 2020-05-28 20:10
> Permissions issues?

Yeah, I have resolved this issue.

**Comment by TeAmP0is0N** [comment] 2020-05-28 20:14
Yeah, it worked. Now, everything has resolved. Thanks a lot. It's ready to go.

**Comment by ChrisRackauckas** [comment] 2020-05-28 20:15
Awesome!

**Closed by ChrisRackauckas** 2020-05-28 20:15 UTC
