### ISSUE TITLE
Run solve on vectors in NNODE_tests.jl

### ISSUE THREAD

**Issue by vavrines** [SciML/NeuralNetDiffEq.jl#80] opened 2020-04-20 20:46 UTC
Hi there,

I just tried the test cases in NNODE_tests.jl and the illustrative codes work perfect.
However, when I tried to add a real row vector like MNIST perception, it gives the dimension dismatch error from Zygote.

The codes are:

```
linear = (u, p, t) -> @. t - u*t
tspan = (0.0f0, 1.0f0)
u0 = [0.0f0 0.0f0]
prob = ODEProblem(linear, u0 ,tspan)
chain = Flux.Chain(Dense(1, 5, σ), Dense(5, 1))

opt = Flux.ADAM(0.1, (0.9, 0.95))
sol = solve(prob, NeuralNetDiffEq.NNODE(chain, opt), dt=1/50f0, verbose=true, abstol=1e-10, maxiters=10)
```
And the errors are
```
DimensionMismatch("dimensions must match")

Stacktrace:
 [1] promote_shape at ./indices.jl:159 [inlined]
 [2] promote_shape at ./indices.jl:145 [inlined]
 [3] +(::Array{Float32,2}, ::Array{Float32,1}) at ./arraymath.jl:45
 [4] adjoint at /home/tianbai/.julia/packages/Zygote/KNUTW/src/lib/array.jl:773 [inlined]
 [5] _pullback(::Zygote.Context, ::typeof(+), ::Array{Float32,2}, ::Array{Float32,1}) at /home/tianbai/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:47
 [6] #6 at /home/tianbai/.julia/packages/NeuralNetDiffEq/skSLw/src/ode_solve.jl:63 [inlined]
 [7] _pullback(::Zygote.Context, ::NeuralNetDiffEq.var"#6#17"{Array{Float32,2},Tuple{Float32,Float32},Flux.var"#12#14"{Chain{Tuple{Dense{typeof(σ),Array{Float32,2},Array{Float32,1}},Dense{typeof(identity),Array{Float32,2},Array{Float32,1}}}}}}, ::Float32, ::Array{Float32,1}) at /home/tianbai/.julia/packages/Zygote/KNUTW/src/compiler/interface2.jl:0
 [8] _pullback(::Zygote.Context, ::NeuralNetDiffEq.var"#9#20", ::Float32, ::Array{Float32,1}) at /home/tianbai/.julia/packages/NeuralNetDiffEq/skSLw/src/ode_solve.jl:70
 [9] _pullback(::Zygote.Context, ::NeuralNetDiffEq.var"#inner_loss#21"{ODEFunction{false,var"#63#64",LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},DiffEqBase.NullParameters}, ::Float32, ::Array{Float32,1}) at /home/tianbai/.julia/packages/NeuralNetDiffEq/skSLw/src/ode_solve.jl:74
 [10] #10 at ./none:0 [inlined]
...
```

Instead of using a loop to iterate every scalar over the vector, I wonder if there is a smarter way to handle this?

Thx : )

**Comment by KirillZubov** [comment] 2020-04-21 18:06
@vavrines I fixed that. Now your code should work in master.

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:08
@KirillZubov why broadcast there? Why are the sizes not lining up?

**Comment by KirillZubov** [comment] 2020-04-21 18:14
@ChrisRackauckas  we used the `phi` function for scalars and not for vectors.  https://github.com/SciML/NeuralNetDiffEq.jl/commit/6183315e0e9e8442191c50b6f014dbd0f3e3099b#diff-01a78f91139818e96d7b261cd47ca62fL63

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:16
Yes, but why is that an issue? `rand(2) * 0.1rand(2)` is a perfectly fine piece of code that doesn't error and matches the calculation that phi should be doing.

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:17
Why do all of these tests on Lotka-Volterra work (https://github.com/SciML/NeuralNetDiffEq.jl/issues/46) but for some reason this fails? I think this just needs more investigating before concluding that broadcast is the right answer.

**Comment by KirillZubov** [comment] 2020-04-21 18:22
@ChrisRackauckas  ok, I see. I more investigating it.

**Comment by ashutosh-b-b** [comment] 2020-04-21 18:33
`phi = (t,θ) -> u0 + (t-tspan[1])*chain(adapt(typeof(θ),[t]),θ)` @KirillZubov Here u0 is 1 X 2 array and the other part is a vector. Which in this case is 1 element.( the chain's output should be 2 in the first place).

**Comment by ashutosh-b-b** [comment] 2020-04-21 18:37
The difference arrises due to addition of different dimensions.

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:39
Let's make `u0 = [0.0f0 0.0f0]` into `u0 = [0.0f0,0.0f0]`. Still errors I think.

To be clear why I think it's important to look into this, the fact that `rand(2) * 0.1rand(2)` works but this line of code in the package doesn't is quite odd: it means a shape is changing somewhere. If you accidentally broadcast a vector to a row vector, `rand(2) .+ rand(2)'`, you get a matrix. If we then are summing after that, we can still get a scalar out, but just not the scalar we were hoping to calculate. So this could be pointing to something that is a deeper bug, and `.+` could "fix it" but calculate the wrong thing and give wrong gradients, so we should be careful to know this is actually the fix we need.

**Comment by KirillZubov** [comment] 2020-04-21 18:41
@vavrines @ChrisRackauckas  oh, I understood it just needs `chain = Flux.Chain(Dense(1, 5, σ), Dense(5, 2))` output neural network should be of the same dimension as u0.

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:42
So yeah actually, looking again... it's user error. Two errors to be exact. And the fact that the fix "works" is why it needs to be reverted. Let me explain.

The issue is `chain = Flux.Chain(Dense(1, 5, σ), Dense(5, 1))` the chain only has one output, so it's not correctly a neural network representing `u(t)` since `u(t) = [x(t),y(t)]`. So first of all, that needs to change to `Flux.Chain(Dense(1, 5, σ), Dense(5, 2))`. Secondly, you'll get an error because the user made the initial condition defined on a row vector, not a regular vector, because of `u0 = [0.0f0 0.0f0]`. So they either need to do `Flux.Chain(Dense(1, 5, σ), Dense(5, 2),x->reshape(x,1,2))` or, more sensibly, use a vector. So the working code is:

```julia
using NeuralNetDiffEq
linear = (u, p, t) -> @. t - u*t
tspan = (0.0f0, 1.0f0)
u0 = [0.0f0,0.0f0]
prob = ODEProblem(linear, u0 ,tspan)
chain = Flux.Chain(Dense(1, 5, σ), Dense(5, 2))

opt = Flux.ADAM(0.1, (0.9, 0.95))
sol = solve(prob, NeuralNetDiffEq.NNODE(chain, opt), dt=1/50f0, verbose=true, abstol=1e-10, maxiters=10)
```

**Comment by ashutosh-b-b** [comment] 2020-04-21 18:48
I think there's no need to put an update with `.+` or reshape then.

**Comment by KirillZubov** [comment] 2020-04-21 18:49
yep, I will push back the changes

**Comment by vavrines** [comment] 2020-04-21 18:54
Thx for pointing out that and all the discussions : )

**Comment by ChrisRackauckas** [comment] 2020-04-21 18:57
I wonder if we can throw a better error here, since that error is quite obscure...

**Comment by ChrisRackauckas** [comment] 2020-07-11 20:27
This was fixed and we forgot to close the issue.

**Closed by ChrisRackauckas** 2020-07-11 20:27 UTC
